### ISSUE TITLE
Support for Roam v1

### ISSUE THREAD

**Issue by markdon0101** [BadmanBarista/wahoo-vtm-themer#1]
I noticed that your earlier xmls included layers for the original bolt and roam, but newer versions exclude these models.
Perhaps this was a change at wahoo.

Would it be possible to simply rename a layer to ROAM, cat id=roam and use the provided xml on my Roam v1 device?
My goal is to add park/greenspace visibility on the original roam.  
The device can display the color green, but doesn't use it for green spaces as it does on version 2.

[edit] this does work!
I now have green and red and other colors shown on the Roam v1 map.
In addition to renaming ROAM_2 to ROAM and roam2 to roam, I added the cfg_BHomeActivity_VtmMaps empty file to the root of my device which you had mentioned elsewhere to get the device using the vtm rendering.

**Comment by Kranex** [comment]
@markdon0101 you are correct! Looks like wahoo has removed the themes for the v1 roam and bolt. You might run into contrast issues by renaming the V2 profiles, looking at the old themes the v1's were explicitly black and white. 

Is the roam v1 still receiving software updates? It might be they have a different theme file now, I can look for it in a bit.

**Comment by BadmanBarista** [comment]
@markdon0101 you are correct! Looks like wahoo has removed the themes for the v1 roam and bolt. You might run into contrast issues by renaming the V2 profiles, looking at the old themes the v1's were explicitly black and white.

Is the roam v1 still receiving software updates? It might be they have a different theme file now, I can look for it in a bit.
